services:
  db: 
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: auth

    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  db_data:

